language: node_js
node_js:
  - "4.3.0"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
env:
  global:
  - JWT_SECRET="EverythingIsAwesome!"
services:
  - redis-server
